name: 4ngle4pk Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'MANIFEST_URL (if want to use SSH keys, use git@github.com:XXXXX)'
        required: true
        default: 'https://github.com/naz664/treble_manifest.git'
      BUILD_TARGET:
        description: 'BUILD_TARGET'
        required: true
        default: 'crDroid-OS'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:   
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"


    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v3
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps'

    - name: Install dependencies
      run: |
           sudo apt-get update
           sudo apt-get install python3
           git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
           echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
           export PATH=~/depot_tools:$PATH
           cd depot_tools
           wget https://storage.googleapis.com/chrome-infra-packages/store/SHA256/bb4335862abfe32d7b24f1bc39bfefb0e108bb2b6250b3531905c171b98f2f1b?Expires=1702845236&GoogleAccessId=chrome-infra-packages%40appspot.gserviceaccount.com&Signature=i3GJwWdPQYzteaHZw3zEJbQ96TNcL4drm0AxMbpyQAEsWqIAmWkb7owLz69Qg72xQF73NW4chUTXh8%2BkoObj3JlmOK1nYGbOV44d%2FXSk8crbHql5QoX%2FMLI6gEuM%2BU2HkgfGBfXhHX40Iex2FtmmGiig41vaWkSGuRnTnimhC6%2BdcZWFhf5hCR8xBumoPzVc8unCBcPPXGPhdOrAacl7J5bqgIwHzuiGegEep9qcYK8eDWlq%2BvS4qGCtuc2Mba17OScuZqB2iVnWOcv3y7WWrS%2FAGkuVaVERXFTHtzBiUKkxYwQ3hYioKWesRu%2FZ6uN8O0i7oqTr6X6zyx5CVfCjJQ%3D%3D&response-content-disposition=attachment%3B+filename%3D%22ninja-linux-arm64.zip%22
           extract ninja-linux-arm64.zip
           cd ..
           echo "$GITHUB_WORKSPACE/depot_tools/ninja" >> $GITHUB_PATH 
           export PATH=~/depot_tools/ninja:$PATH

      
    - name: Angle 1
      run: |
           mkdir angle
           cd angle
           fetch angle
           ./build/install-build-deps.sh
    
    - name: Angle main
      run: |
            mkdir -p out/Android
            autoninja -C out/Android


