name: 4ngle4pk Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'MANIFEST_URL (if want to use SSH keys, use git@github.com:XXXXX)'
        required: true
        default: 'https://github.com/naz664/treble_manifest.git'
      BUILD_TARGET:
        description: 'BUILD_TARGET'
        required: true
        default: 'crDroid-OS'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:   
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"


    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v3
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps'

    - name: Install dependencies
      run: |
           sudo apt-get update
           sudo apt-get install python3
           git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
           echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
           export PATH=~/depot_tools:$PATH
           sudo apt install ninja-build

      
    - name: Angle 1
      run: |
           mkdir angle
           cd angle
           fetch angle
           ./build/install-build-deps.sh
           gn gen out/Android --args='target_os = "android" target_cpu = "arm64" angle_enable_vulkan = true is_component_build = false is_debug = false'
      
    
    - name: Angle main
      run: |
        autoninja -C out/Android angle_apks


